version: '3'
services:
  db_service:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sectionb
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  backend_service:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:app
    ports:
      - "8000:8000"

    environment:
      - POSTGRES_DB=sectionb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

    depends_on:
      - db_service
 

volumes:
  postgres_data: